name: smart_dialogs_plus_example
description: Demonstrates the usage of the smart_dialogs_plus package.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smart_dialogs_plus:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/smart_dialogs_plus/