name: smart_dialogs_plus
description: "A Flutter package for smart animated dialogs, alerts, snackbars, and loaders with controller and Lottie support."
version: 0.0.4
homepage: https://pub.dev/packages/smart_dialogs_plus
repository: https://github.com/akikadigital/smart_dialogs_plus
issue_tracker: https://github.com/akikadigital/smart_dialogs_plus/issues
documentation: https://pub.dev/packages/smart_dialogs_plus

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - screenshots/

topics:
  - flutter
  - dialogs
  - progress
  - snackbar
  - alerts
